# Initial Setup

In [1]:
# Import tweepy 
import tweepy
from config import *

In [10]:
# Import other dependencies
import pandas as pd
from datetime import datetime, date
import json

In [3]:
# More
import matplotlib.pyplot as plt 
import numpy as np 
from textblob import TextBlob
from wordcloud import WordCloud 
import re

In [4]:
# Tweepy Setup
auth = tweepy.OAuthHandler(api_key, api_secret_key)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)

In [19]:
# Define some search terms
# Limited number of API calls so want to limit unusable data 

search_terms = ['covid+vaccine OR covid-19+vaccine OR pfizer OR pfizer-biontech OR moderna OR astrazeneca OR astra+zeneca -filter:retweets']
end_date = date(2021,3,4)
limit = 18000
end_date

datetime.date(2021, 3, 4)

In [13]:
def GetTweets(end_date, search_terms, limit):
    data = []
    raw = []
    tweets = tweepy.Cursor(api.search, until=end_date, max_id ='1367261441515016193', location='canada', place='canada', lang ='en', q=search_terms, tweet_mode='extended').items(limit)
    for t in tweets: 
        tweet ={
            'created' :t.created_at,
            'id_str' : t.id_str,
            'text' : t.full_text,
            'user_id' :t.user.id,
            'screen_name': t.user.screen_name,
            'location': t.user.location,
            'followers_count': t.user.followers_count,
            'user_favourites_count': t.user.favourites_count,
            'time_zone' :t.user.time_zone,
            'geo_enabled' :t.user.geo_enabled,
            'verified' :t.user.verified,
            'status_count': t.user.statuses_count,
            'geo':t.geo,
            'coords':t.coordinates,
            'place':t.place,
            'retweet_count': t.retweet_count,
            'tweet_favourite_count' : t.favorite_count,
            'retweeted' : t.retweeted,
            'lang':t.lang
        }
    # add sorted data to one list 
        data.append(tweet)
    # keep raw data in case I realize later that I've removed something important 
        raw.append(t)
    tweets_df = pd.DataFrame(data)
    tweets_df.to_csv('tst.csv', index=False, encoding='UTF-8')
    with open('tst.json', 'w') as file:
        for resp in raw:
            jso = json.dumps(resp._json,sort_keys=True, indent=3)
            file.write(jso)

In [20]:
data = []
raw = []
tweets = tweepy.Cursor(api.search, location='canada', place='canada', lang ='en', q=search_terms, tweet_mode='extended').items(limit)
for t in tweets: 
    tweet ={
        'created' :t.created_at,
        'id_str' : t.id_str,
        'text' : t.full_text,
        'user_id' :t.user.id,
        'screen_name': t.user.screen_name,
        'location': t.user.location,
        'followers_count': t.user.followers_count,
        'user_favourites_count': t.user.favourites_count,
        'time_zone' :t.user.time_zone,
        'geo_enabled' :t.user.geo_enabled,
        'verified' :t.user.verified,
        'status_count': t.user.statuses_count,
        'geo':t.geo,
        'coords':t.coordinates,
        'place':t.place,
        'retweet_count': t.retweet_count,
        'tweet_favourite_count' : t.favorite_count,
        'retweeted' : t.retweeted,
        'lang':t.lang
    }
    # add sorted data to one list 
    data.append(tweet)
    # keep raw data in case I realize later that I've removed something important 
    raw.append(t)
tweets_df = pd.DataFrame(data)
tweets_df.to_csv('tweets2.csv', index=False, encoding='UTF-8')
with open('raw2.json', 'w') as file:
    for resp in raw:
        jso = json.dumps(resp._json,sort_keys=True, indent=3)
        file.write(jso)
tweets_df.tail()

TweepError: Twitter error response: status code = 429

# Initial Testing of Tweet scrape
Run a few times to pick out useful data and save a backup of what was pulled to json

In [22]:
# Create empty containers for scraped data 
data = []
raw =[]

# Create api call 
tweets = tweepy.Cursor(api.search, until=end_date, location='canada', place='canada', lang ='en', q=search_terms, tweet_mode='extended').items(limit)
# parse response for useful data 
for t in tweets: 
    tweet ={
        'created' :t.created_at,
        'id_str' : t.id_str,
        'text' : t.full_text,
        'user_id' :t.user.id,
        'screen_name': t.user.screen_name,
        'location': t.user.location,
        'followers_count': t.user.followers_count,
        'user_favourites_count': t.user.favourites_count,
        'time_zone' :t.user.time_zone,
        'geo_enabled' :t.user.geo_enabled,
        'verified' :t.user.verified,
        'status_count': t.user.statuses_count,
        'geo':t.geo,
        'coords':t.coordinates,
        'place':t.place,
        'retweet_count': t.retweet_count,
        'tweet_favourite_count' : t.favorite_count,
        'retweeted' : t.retweeted,
        'lang':t.lang
    }
    # add sorted data to one list 
    data.append(tweet)
    
    # keep raw data in case I realize later that I've removed something important 
    raw.append(t)

data[0]

{'created': datetime.datetime(2021, 3, 3, 23, 59, 59),
 'id_str': '1367263516457979910',
 'text': '@Shieldk2 Yes! My wife works for Pfizer and has been working on that vax nonstop since April 2020',
 'user_id': 2600327203,
 'screen_name': 'Sobres74',
 'location': 'Seattle, WA',
 'followers_count': 91,
 'user_favourites_count': 2960,
 'time_zone': None,
 'geo_enabled': False,
 'verified': False,
 'status_count': 3192,
 'geo': None,
 'coords': None,
 'place': None,
 'retweet_count': 0,
 'tweet_favourite_count': 1,
 'retweeted': False,
 'lang': 'en'}

In [23]:
len(data)

1000

In [24]:
tweets_df = pd.DataFrame(data)
tweets_df.tail()

,created,id_str,text,user_id,screen_name,location,followers_count,user_favourites_count,time_zone,geo_enabled,verified,status_count,geo,coords,place,retweet_count,tweet_favourite_count,retweeted,lang
995,2021-03-03 23:51:47,1367261453305212932,"RT @KamiRieck: Diana Rastegayeva, a mother who...",3354131177,shalondajones30,DMV,1823,111198,None,True,False,91645,None,None,None,608,0,False,en
996,2021-03-03 23:51:46,1367261449026822144,RT @carolynstrom: Have you switched from a lan...,50794700,KatelinCuthill,"Saskatchewan, Canada",541,5381,None,True,False,5051,None,None,None,3,0,False,en
997,2021-03-03 23:51:46,1367261447135371264,RT @cityofhamilton: We are noting reports of a...,1364388107253080070,SadiyaK5,GTA,16,223,None,False,False,385,None,None,None,172,0,False,en
998,2021-03-03 23:51:45,1367261444597817350,Hell yes! I live in Florida. Did you know DeSa...,1353703600552353793,RNjudyFlorida,"Hobe Sound, FL",94,1440,None,False,False,688,None,None,None,0,0,False,en
999,2021-03-03 23:51:44,1367261441515016193,"@GOPChairwoman I dunno, maybe fixing Trump's v...",1264926857679560706,erbach_paul,,17,9358,None,False,False,1244,None,None,None,0,0,False,en

In [25]:
tweets_df.to_csv('tweets1.csv', index=False, encoding='UTF-8')

In [30]:
# raw 
import json
with open('raw1.json', 'w') as file:
    for resp in raw:
        jso = json.dumps(resp._json,sort_keys=True, indent=3)
        file.write(jso)

In [ ]:
# limit 100,000 / d
# 18,000 / 15min

In [ ]:
# possible source of extra tweets 
# https://github.com/thepanacealab/covid19_twitter

# Perfecting the code
A trail dataset is bein used to test out data cleaning and graphing so that I don't waste my limited api calls

In [68]:
df = pd.read_csv('Tweets.csv')
df = df[['tweet_id', 'airline','name','retweet_count','text', 'tweet_created','latitude', 'longitude']]
df = df.rename(columns={'tweet_id':'id_str', 'tweet_created':'created'}) # changed to match output of 
df.head()

,id_str,airline,name,retweet_count,text,created,latitude,longitude
0,5.703061e+17,Virgin America,cairdin,0,@VirginAmerica What @dhepburn said.,2015-02-24 11:35:52 -0800,35.888455,-119.273781
1,5.703011e+17,Virgin America,jnardino,0,@VirginAmerica plus you've added commercials t...,2015-02-24 11:15:59 -0800,37.770971,-119.941025
2,5.703011e+17,Virgin America,yvonnalynn,0,@VirginAmerica I didn't today... Must mean I n...,2015-02-24 11:15:48 -0800,35.684863,-119.709299
3,5.703010e+17,Virgin America,jnardino,0,@VirginAmerica it's really aggressive to blast...,2015-02-24 11:15:36 -0800,37.061159,-119.279135
4,5.703008e+17,Virgin America,jnardino,0,@VirginAmerica and it's a really big bad thing...,2015-02-24 11:14:45 -0800,36.790587,-120.867752

In [69]:
len(df)

14640

In [42]:
df = df.drop_duplicates(subset='id_str')
len(df)

14485

In [72]:
df['date'] = df['created'].str.split(' ').str[0]
df= df.drop(columns=['created'])
df.head()

,id_str,airline,name,retweet_count,text,latitude,longitude,date
0,5.703061e+17,Virgin America,cairdin,0,@VirginAmerica What @dhepburn said.,35.888455,-119.273781,2015-02-24
1,5.703011e+17,Virgin America,jnardino,0,@VirginAmerica plus you've added commercials t...,37.770971,-119.941025,2015-02-24
2,5.703011e+17,Virgin America,yvonnalynn,0,@VirginAmerica I didn't today... Must mean I n...,35.684863,-119.709299,2015-02-24
3,5.703010e+17,Virgin America,jnardino,0,@VirginAmerica it's really aggressive to blast...,37.061159,-119.279135,2015-02-24
4,5.703008e+17,Virgin America,jnardino,0,@VirginAmerica and it's a really big bad thing...,36.790587,-120.867752,2015-02-24

In [75]:
df['date'] = pd.to_datetime(df['date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14640 entries, 0 to 14639
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_str         14640 non-null  float64
 1   airline        14640 non-null  object
 2   name           14640 non-null  object
 3   retweet_count  14640 non-null  int64
 4   text           14640 non-null  object
 5   latitude       14640 non-null  float64
 6   longitude      14640 non-null  float64
 7   date           14640 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 915.1+ KB

In [73]:
def CleanFrame(df):
    df = df.drop_duplicates(subset='id_str')
    df['date'] = df['created'].str.split(' ').str[0]
    df = df.drop(columns=['created'])
    df['date'] = pd.to_datetime(df['date'])
    return df

In [74]:
CleanFrame(df)
df.head()

KeyError: 'created'

In [31]:
def CleanTweets(txt): 
    # remove @ username 
    # txt = re.sub(r'@[A-Za-z0-9)]+','', txt)
    
    # remove RT    
    txt = re.sub(r'RT[\s]+','',txt)
    
    # remove @ from username
    txt = txt.replace('@','')
    
    # remove # but leave txt
    txt = re.sub(r'#','', txt)
    
    # remove hyperlinks
    txt = re.sub(r'https?:\/\/\S+', '', txt)
    
    return txt

In [80]:
df['text'] = df['text'].apply(CleanTweet)
df.head()

,id_str,airline,name,retweet_count,text,latitude,longitude,date,Subjectivity,Polarity
0,5.703061e+17,Virgin America,cairdin,0,VirginAmerica What dhepburn said.,35.888455,-119.273781,2015-02-24,0.000000,0.000000
1,5.703011e+17,Virgin America,jnardino,0,VirginAmerica plus you've added commercials to...,37.770971,-119.941025,2015-02-24,0.000000,0.000000
2,5.703011e+17,Virgin America,yvonnalynn,0,VirginAmerica I didn't today... Must mean I ne...,35.684863,-119.709299,2015-02-24,0.687500,-0.390625
3,5.703010e+17,Virgin America,jnardino,0,VirginAmerica it's really aggressive to blast ...,37.061159,-119.279135,2015-02-24,0.350000,0.006250
4,5.703008e+17,Virgin America,jnardino,0,VirginAmerica and it's a really big bad thing ...,36.790587,-120.867752,2015-02-24,0.383333,-0.350000

In [76]:
# to get subjectivity 
def RateSubjectivity(txt):
    return TextBlob(txt).sentiment.subjectivity

In [77]:
# to get polarity
def RatePolarity(txt):
    return TextBlob(txt).sentiment.polarity

In [81]:
# Create Columns
df['Subjectivity'] = df['text'].apply(RateSubjectivity)
df['Polarity'] = df['text'].apply(RatePolarity)
df.head()

,id_str,airline,name,retweet_count,text,latitude,longitude,date,Subjectivity,Polarity
0,5.703061e+17,Virgin America,cairdin,0,VirginAmerica What dhepburn said.,35.888455,-119.273781,2015-02-24,0.000000,0.000000
1,5.703011e+17,Virgin America,jnardino,0,VirginAmerica plus you've added commercials to...,37.770971,-119.941025,2015-02-24,0.000000,0.000000
2,5.703011e+17,Virgin America,yvonnalynn,0,VirginAmerica I didn't today... Must mean I ne...,35.684863,-119.709299,2015-02-24,0.687500,-0.390625
3,5.703010e+17,Virgin America,jnardino,0,VirginAmerica it's really aggressive to blast ...,37.061159,-119.279135,2015-02-24,0.350000,0.006250
4,5.703008e+17,Virgin America,jnardino,0,VirginAmerica and it's a really big bad thing ...,36.790587,-120.867752,2015-02-24,0.383333,-0.350000

In [ ]:
# Plot Word Cloud